### ISSUE TITLE
About the [Tab]

### ISSUE THREAD

**Issue by ccviolett** [Kewth/retest#4]
It will throw error when write the `retest.yaml` using `\t`, like:

```
T1:
\t source: xxxx
\t date: xxxx
```

Sorry about can't enter [Tab] in github.

Can you fix it?

**Comment by Kewth** [comment]
I don't know why there's such a problem yet.

But i'll try to fix it.

**Comment by ghost** [comment]
It's not ntest.py's fault.

From [yaml official site](https://yaml.org/spec/1.2/spec.html#id2777534):
> To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently. Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces. 

The standard refuses **tab**.

**Comment by Kewth** [comment]
> It's not ntest.py's fault.
> 
> From [yaml official site](https://yaml.org/spec/1.2/spec.html#id2777534):
> 
> > To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently. Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces.
> 
> The standard refuses **tab**.

I read this, to find that my editor use space instead of a tab when I'm trying to edit .yaml.
