### ISSUE TITLE
求win如何安装

### ISSUE THREAD

**Issue by eventlOwOp** [Kewth/retest#5]
超级好评
但请问win系统如何安装
谢谢

**Comment by Kewth** [comment]
只要 windows 上能用 python3 就行，用 python3 运行 neo.py 就行了。  
但是 ntest 是为终端设计的，直接跑肯定会有问题，所以最好还是用 linux 。

**Comment by Kewth** [comment]
好吧不行，抱歉，ntest 只支持 linux 。
